#!/bin/bash
v="v1.1.8"

cd $(mktemp -d) &&
git clone https://github.com/binance-chain/bsc &&
cd bsc &&
git checkout $v &&
docker build . -t joleman/bsc:$v -t joleman/bsc:latest &&
docker push joleman/bsc --all-tags
