#!/usr/bin/bash
cd $(mktemp -d) &&
git clone https://github.com/maticnetwork/bor &&
cd bor &&
git checkout 6f5915363e57c61457d35c9f492628a54b0ad110 &&
docker build . -t joleman/bor:latest &&
docker push joleman/bor:latest
