#!/usr/bin/bash
cd $(mktemp -d) &&
git clone https://github.com/ethereum/go-ethereum &&
cd go-ethereum &&
git checkout v1.10.11 &&
docker build . -t joleman/eth:latest &&
docker push joleman/eth:latest
