[Eth]
NetworkId = 137
SyncMode = "fast"
NoPruning = false
NoPrefetch = false
LightPeers = 1
UltraLightFraction = 75
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 500000000000
#TrieTimeout = 3600000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
DatabaseCache = 12000

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 5600000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 70
OracleThreshold = 20

[Node]
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 9575
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 9546
WSModules = ["net", "web3", "eth"]
#GraphQLPort = 9557
GraphQLVirtualHosts = ["*"]

[Node.P2P]
MaxPeers = 120
NoDiscovery = false
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
