services:
        bsc-node:
                image: joleman/bsc
                network_mode: "host"
                command:
                        --config /data/config.toml
                        --datadir /node
                        --cache 12288
                        --nat none
                        --snapshot=false
                volumes:
                        - ./node:/node
                        - ./data:/data
                restart: always
