services:
        kcc-node:
                image: joleman/kcc
                network_mode: "host"
                command:
                        --config /data/config.toml
                        --datadir /node
                        --cache 12288
                        --nat none
                        #--snapshot=false
                volumes:
                        - ./node:/node
                        - ./data:/data
                restart: always
        kcc-prune:
                image: joleman/kcc
                network_mode: "host"
                command:
                        --datadir /node
                        snapshot prune-state
                volumes:
                        - ./node:/node
                        - ./data:/data
                restart: always
