#!/usr/bin/bash
mkdir -p node data &&
cp -f config.toml data/ &&

bef=$(pwd)
cd $(mktemp -d) &&
wget https://raw.githubusercontent.com/kcc-community/kcc/kcc/genesis-mainnet.json -O genesis.json &&
cp genesis.json $bef &&
cd $bef &&

./geth --datadir ./node init genesis.json &&
rm genesis.json
