#!/usr/bin/bash
mkdir -p node data &&
cp -f config.toml data/ &&

bef=$(pwd)
cd $(mktemp -d) &&
wget $(curl -s https://api.github.com/repos/binance-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4) &&
unzip mainnet.zip &&
cp genesis.json $bef &&
cd $bef &&

geth --datadir ./node init genesis.json &&
rm genesis.json
